import { createReadOnlyLifecycle } from "../../worker/read-only-lifecycle.mjs";
import {readFile} from 'node:fs/promises';
import pg from 'pg';
import {beforeAll,afterAll,beforeEach,it,expect,vi} from 'vitest';
import {NextRequest} from 'next/server';
import {migrate} from '../../scripts/migrate.mjs';
const state=vi.hoisted(()=>({pool:null as unknown as pg.Pool,actor:0,project:0,queueCalls:0,queueObserver:null as null | ((name:string,data:{id?:number})=>Promise<void>)}));
vi.mock('@/lib/db',()=>({getPool:()=>state.pool}));
vi.mock('@/lib/session',()=>({getSessionUser:async()=>({id:state.actor})}));
vi.mock('next/headers',()=>({headers:async()=>new Headers({'x-aurora-project-id':String(state.project)})}));
vi.mock('@/lib/queue',()=>({getStatsQueue:()=>({add:async(name:string,data:{id?:number})=>{state.queueCalls++;await state.queueObserver?.(name,data);return{id:'fake'};}})}));
vi.mock('@/lib/radar-search-queue',()=>({enqueueRadarSearch:async()=>{state.queueCalls++;}}));
import * as competitor from '@/app/api/competitors/[id]/route';
import * as alerts from '@/app/api/radar/alerts/route';
import * as radar from '@/app/api/radar/search/route';
import * as result from '@/app/api/radar/results/[id]/route';
import * as addCompetitor from '@/app/api/competitors/add/route';
import {selectDueCompetitorSources} from '../../worker/reconnaissance-schedule.mjs';
import {requireResearchWorkerScope, requireRadarWorkerScope, withResearchWorkerWrite} from '../../worker/research-project-scope.mjs';
import {withSelectedProjectPermission} from '@/lib/selected-project-transaction';
const target=new URL(process.env.MIGRATION_TEST_DATABASE_URL||'postgres://invalid/invalid');
if(!['127.0.0.1','localhost','[::1]'].includes(target.hostname)||target.pathname!=='/aurora_domain_review_test'||process.env.DATABASE_URL)throw Error('Explicit isolated aurora_domain_review_test and no inherited app DB required');
const pool=new pg.Pool({connectionString:target.href,max:3});state.pool=pool;
let actor=0,collaborator=0,pa=0,pb=0,ca=0,cb=0,comp=0,alert=0,run=0,res=0;
function req(path:string,method='GET',body?:unknown){return new NextRequest('http://localhost:3000'+path,{method,headers:{origin:'http://localhost:3000','content-type':'application/json','x-aurora-project-id':String(state.project)},...(body?{body:JSON.stringify(body)}:{})});}
const ctx=()=>({params:Promise.resolve({id:String(comp)})});
beforeAll(async()=>{
 process.env.APP_URL='http://localhost:3000';process.env.AURORA_OUTBOUND_DISABLED='1';
 await pool.query('drop schema public cascade');await pool.query('create schema public');
 await pool.query(await readFile(new URL('../../db/schema.sql',import.meta.url),'utf8'));await migrate({env:{DATABASE_URL:target.href},logger:{log(){}}});
 state.actor=Number((await pool.query("insert into users(email)values('domain-review@example.invalid')returning id")).rows[0].id);
 actor=state.actor;collaborator=Number((await pool.query("insert into users(email)values('domain-author@example.invalid')returning id")).rows[0].id);
 for(const label of ['A','B']){const id=Number((await pool.query('insert into projects(name,created_by_user_id)values($1,$2)returning id',[label,state.actor])).rows[0].id);if(label==='A')pa=id;else pb=id;await pool.query("insert into project_members(project_id,user_id,role)values($1,$2,'owner')",[id,state.actor]);}
 await pool.query("insert into project_members(project_id,user_id,role)values($1,$2,'author')",[pa,collaborator]);
 await pool.query('insert into user_project_preferences(user_id,selected_project_id)values($1,$2)',[state.actor,pb]);
 for(const [p,label]of[[pa,'A'],[pb,'B']]as const){const id=Number((await pool.query("insert into channels(user_id,project_id,network,tg_chat_id,title,status,is_active)values($1,$2,'tg',$3,$4,'active',true)returning id",[state.actor,p,-100500000-p,label])).rows[0].id);if(p===pa)ca=id;else cb=id;}
 comp=Number((await pool.query("insert into competitors(user_id,channel_id,network,handle,title,status)values($1,$2,'tg','canary_revoked','канарейка','ready')returning id",[state.actor,ca])).rows[0].id);
 alert=Number((await pool.query("insert into niche_alerts(user_id,channel_id,keyword)values($1,$2,'канарейка')returning id",[state.actor,ca])).rows[0].id);
 run=Number((await pool.query("insert into radar_search_runs(user_id,channel_id,project_id,request_key,query,normalized_query,status,stage)values($1,$2,$3,'domain-review','канарейка','канарейка','ready','ready')returning id",[state.actor,ca,pa])).rows[0].id);
 res=Number((await pool.query("insert into radar_search_results(run_id,user_id,result_type,provider,canonical_key,url,title,text,reason,quality_score,relevance_score)values($1,$2,'post','fixture','fixture','https://example.invalid/canary','канарейка','канарейка','synthetic',90,90)returning id",[run,state.actor])).rows[0].id);
});
afterAll(async()=>pool.end());
beforeEach(async()=>{state.actor=actor;state.project=pb;state.queueCalls=0;state.queueObserver=null;await pool.query('update projects set is_archived=false');await pool.query('update users set blocked_at=null');await pool.query("update project_members set status='active',revoked_at=null,role=case when user_id=$1 then 'author' else 'owner' end",[collaborator]);await pool.query('update competitors set is_active=true');await pool.query('delete from saved_posts');await pool.query('delete from niche_matches');await pool.query('delete from competitor_posts');await pool.query('update niche_alerts set last_notified_at=null');await pool.query("update project_members set status='revoked',revoked_at=now() where project_id=$1 and user_id=$2",[pa,state.actor]);});
it('N21: denies competitor dossier created by actor after project revoke and selecting B',async()=>{const response=await competitor.GET(req(`/api/competitors/${comp}`),ctx());const body=await response.json();console.log('OBS competitor read',response.status,body.competitor?.handle);expect([403,404]).toContain(response.status);});
it('N21: denies competitor mutation after revoke, preserves active state',async()=>{const response=await competitor.PATCH(req(`/api/competitors/${comp}`,'PATCH',{action:'pause'}),ctx());const row=(await pool.query('select is_active from competitors where id=$1',[comp])).rows[0];console.log('OBS competitor mutation',response.status,row.is_active);expect(row.is_active).toBe(true);expect([403,404]).toContain(response.status);});
it('N21: selected B alert list cannot include revoked project A',async()=>{const response=await alerts.GET(req('/api/radar/alerts'));const body=await response.json();console.log('OBS alert read',response.status,body.alerts?.map((a:{channel_id:number})=>a.channel_id));expect(body.alerts?.some((a:{id:number})=>Number(a.id)===alert)).not.toBe(true);});
it('N21: cannot create new alert in revoked channel',async()=>{const response=await alerts.POST(req('/api/radar/alerts','POST',{channelId:ca,keyword:'new-after-revoke'}));const count=Number((await pool.query("select count(*) from niche_alerts where channel_id=$1 and keyword='new-after-revoke'",[ca])).rows[0].count);console.log('OBS alert mutation',response.status,count);expect(count).toBe(0);expect([403,404,422]).toContain(response.status);});
it('N21: radar run cursor cannot return revoked project results',async()=>{const response=await radar.GET(req(`/api/radar/search?run=${run}`));const body=await response.json();console.log('OBS radar run',response.status,body.results?.length);expect([403,404]).toContain(response.status);});
it('N21: cannot copy revoked project radar result into selected B',async()=>{const response=await result.POST(req(`/api/radar/results/${res}`,'POST',{action:'save_reference',channelId:cb}),{params:Promise.resolve({id:String(res)})});const count=Number((await pool.query('select count(*) from saved_posts where channel_id=$1',[cb])).rows[0].count);console.log('OBS radar cross-project write',response.status,count);expect(count).toBe(0);expect([403,404]).toContain(response.status);});

it('separates selected project even while both memberships remain active',async()=>{await pool.query("update project_members set status='active',revoked_at=null where project_id=$1 and user_id=$2",[pa,actor]);const response=await competitor.GET(req(`/api/competitors/${comp}`),ctx());expect(response.status).toBe(404);});
it('rejects explicit selected revoked project instead of falling back to preference B',async()=>{state.project=pa;const response=await alerts.GET(req('/api/radar/alerts'));expect(response.status).toBe(403);});
it('rejects archived project and blocked account on fresh reads',async()=>{await pool.query('update projects set is_archived=true where id=$1',[pb]);expect((await alerts.GET(req('/api/radar/alerts'))).status).toBe(403);await pool.query('update projects set is_archived=false where id=$1',[pb]);await pool.query('update users set blocked_at=now() where id=$1',[actor]);expect((await alerts.GET(req('/api/radar/alerts'))).status).toBe(403);});
it('does not delete competitor or alert after project revoke',async()=>{expect((await competitor.DELETE(req(`/api/competitors/${comp}`,'DELETE'),ctx())).status).toBe(404);expect((await alerts.DELETE(req(`/api/radar/alerts?id=${alert}`,'DELETE'))).status).toBe(404);expect((await pool.query('select id from competitors where id=$1',[comp])).rowCount).toBe(1);expect((await pool.query('select id from niche_alerts where id=$1',[alert])).rowCount).toBe(1);});
it('retains lawful author access to shared channel research and mutations',async()=>{state.actor=collaborator;state.project=pa;expect((await competitor.GET(req(`/api/competitors/${comp}`),ctx())).status).toBe(200);expect((await competitor.PATCH(req(`/api/competitors/${comp}`,'PATCH',{action:'pause'}),ctx())).status).toBe(200);expect((await alerts.POST(req('/api/radar/alerts','POST',{channelId:ca,keyword:'collaborator-added'}))).status).toBe(200);const listed=await(await alerts.GET(req('/api/radar/alerts'))).json();expect(listed.alerts.some((row:{id:number})=>Number(row.id)===alert)).toBe(true);});
it('publisher may read research but cannot mutate or queue discovery',async()=>{await pool.query("update project_members set role='publisher' where project_id=$1 and user_id=$2",[pb,actor]);expect((await alerts.GET(req('/api/radar/alerts'))).status).toBe(200);expect((await alerts.POST(req('/api/radar/alerts','POST',{channelId:cb,keyword:'publisher-added'}))).status).toBe(403);expect((await addCompetitor.POST(req('/api/competitors/add','POST',{channelId:cb,handle:'publisher_source'}))).status).toBe(403);expect(state.queueCalls).toBe(0);});
it('dispatches a newly created competitor only after its database row commits',async()=>{let observed=false;state.queueObserver=async(name,data)=>{if(name==='competitor'){observed=(await pool.query('select id from competitors where id=$1',[data.id])).rowCount===1;expect(observed).toBe(true);}};const response=await addCompetitor.POST(req('/api/competitors/add','POST',{channelId:cb,handle:'committed_source'}));expect(response.status).toBe(200);expect(observed).toBe(true);expect(state.queueCalls).toBe(1);});
it('current radar result is usable but a legacy run with no project is held',async()=>{await pool.query('update radar_search_runs set project_id=$1,channel_id=$2 where id=$3',[pb,cb,run]);try{expect((await radar.GET(req(`/api/radar/search?run=${run}`))).status).toBe(200);expect((await result.POST(req(`/api/radar/results/${res}`,'POST',{action:'save_reference',channelId:cb}),{params:Promise.resolve({id:String(res)})})).status).toBe(200);await pool.query('update radar_search_runs set project_id=null where id=$1',[run]);expect((await radar.GET(req(`/api/radar/search?run=${run}`))).status).toBe(404);}finally{await pool.query('update radar_search_runs set project_id=$1,channel_id=$2 where id=$3',[pa,ca,run]);}});
it('does not include a revoked-project cache in a new query in B',async()=>{const response=await radar.GET(req('/api/radar/search?q=канарейка'));expect(response.status).toBe(200);const body=await response.json();expect(body.results.some((row:{actionId:number})=>Number(row.actionId)===res)).toBe(false);});
it('waits for concurrent archive and rechecks after the lock resolves',async()=>{const holder=await pool.connect();await holder.query('begin');await holder.query('update projects set is_archived=true where id=$1',[pb]);let settled=false;const response=alerts.GET(req('/api/radar/alerts')).finally(()=>{settled=true;});let waiting=false;const until=Date.now()+2000;while(!settled&&Date.now()<until){waiting=Number((await pool.query("select count(*) from pg_stat_activity where datname=current_database() and wait_event_type='Lock'")).rows[0].count)>0;if(waiting)break;await new Promise(r=>setTimeout(r,10));}await holder.query('commit');holder.release();expect(waiting).toBe(true);expect((await response).status).toBe(403);});
it('serializes actor-update transactions without share-to-update deadlock',async()=>{const update=(name:string)=>withSelectedProjectPermission(pool,actor,'content.edit',async(client)=>{await client.query('update users set name=$2 where id=$1',[actor,name]);return name;},{actorLock:'update'});expect(await Promise.all([update('first'),update('second')])).toEqual(['first','second']);});

async function nicheRunner(notify: (...args:unknown[])=>Promise<boolean>) {
 const source=await readFile(process.env.N21_NICHE_SOURCE||new URL('../../worker.mjs',import.meta.url),'utf8');
 const start=source.indexOf('async function checkNicheAlerts() {');
 const end=source.indexOf('\n// ── RSS-репостер',start);
 if(start<0||end<0)throw Error('Exact niche worker function not located');
 // Evaluate only the actual function, never import consumers or the worker runtime.
 return new Function('pool','notifyUser','console',source.slice(start,end)+';return checkNicheAlerts;')(pool,notify,{log(){},error(){}}) as ()=>Promise<void>;
}
it('worker never sends niche data to a recipient whose project membership was revoked',async()=>{await pool.query("insert into competitor_posts(competitor_id,tg_msg_id,text,posted_at)values($1,1,'канарейка',now())",[comp]);let calls=0;const check=await nicheRunner(async()=>{calls++;return true;});await check();expect(calls).toBe(0);expect((await pool.query('select id from niche_matches where alert_id=$1',[alert])).rowCount).toBe(0);});
it('niche matching stays inside the alert channel even for the same creator',async()=>{await pool.query("update project_members set status='active',revoked_at=null where project_id=$1 and user_id=$2",[pa,actor]);const other=Number((await pool.query("insert into competitors(user_id,channel_id,network,handle,status)values($1,$2,'tg','niche-other-project','ready')returning id",[actor,cb])).rows[0].id);await pool.query("insert into competitor_posts(competitor_id,tg_msg_id,text,posted_at)values($1,1,'канарейка',now())",[other]);let calls=0;const check=await nicheRunner(async()=>{calls++;return true;});await check();expect(calls).toBe(0);expect((await pool.query('select id from niche_matches where alert_id=$1',[alert])).rowCount).toBe(0);});
it('niche notification uses its durable project and marks delivery only after confirmation',async()=>{await pool.query("update project_members set status='active',revoked_at=null where project_id=$1 and user_id=$2",[pa,actor]);await pool.query("insert into competitor_posts(competitor_id,tg_msg_id,text,posted_at)values($1,1,'канарейка',now())",[comp]);const options:unknown[]=[];const check=await nicheRunner(async(...args)=>{options.push(args[3]);return false;});await check();expect(options).toEqual([{kind:'opportunity',projectId:pa,eventKey:expect.stringMatching(new RegExp('^niche:'+alert+':post:[0-9]+$'))}]);expect((await pool.query('select last_notified_at from niche_alerts where id=$1',[alert])).rows[0].last_notified_at).toBeNull();expect((await pool.query('select notified from niche_matches where alert_id=$1',[alert])).rows[0].notified).toBe(false);});

it('worker denies collection/discovery for revoked, wrong-project or publish-only request actors',async()=>{await expect(requireResearchWorkerScope(pool,actor,ca,pa)).rejects.toMatchObject({message:'research_project_access_denied'});await expect(requireResearchWorkerScope(pool,actor,cb,pa)).rejects.toMatchObject({message:'research_project_access_denied'});await pool.query("update project_members set role='publisher' where project_id=$1 and user_id=$2",[pb,actor]);await expect(requireResearchWorkerScope(pool,actor,cb,pb)).rejects.toMatchObject({message:'research_project_access_denied'});});
it('worker permits an explicit collaborator collection actor without transferring historical creator identity',async()=>{const scope=await requireResearchWorkerScope(pool,collaborator,ca,pa);let writes=0;await withResearchWorkerWrite(pool,scope,async(client)=>{writes++;await client.query("update competitors set title='collaborator-refreshed' where id=$1",[comp]);});expect(writes).toBe(1);expect(Number((await pool.query('select user_id from competitors where id=$1',[comp])).rows[0].user_id)).toBe(actor);});
it('worker rechecks committed revocation after fetch before any result persistence',async()=>{const scope=await requireResearchWorkerScope(pool,actor,cb,pb);await pool.query("update project_members set status='revoked',revoked_at=now() where project_id=$1 and user_id=$2",[pb,actor]);let writes=0;await expect(withResearchWorkerWrite(pool,scope,async()=>{writes++;})).rejects.toMatchObject({message:'research_project_access_denied'});expect(writes).toBe(0);});
it('radar worker requires its durable project, including channel-less searches',async()=>{await expect(requireRadarWorkerScope(pool,run,actor)).rejects.toMatchObject({message:'research_project_access_denied'});await pool.query('update radar_search_runs set project_id=$1,channel_id=null where id=$2',[pb,run]);try{expect(await requireRadarWorkerScope(pool,run,actor)).toMatchObject({projectId:pb,channelId:null,userId:actor});await pool.query('update radar_search_runs set project_id=null where id=$1',[run]);await expect(requireRadarWorkerScope(pool,run,actor)).rejects.toMatchObject({message:'research_project_access_denied'});}finally{await pool.query('update radar_search_runs set project_id=$1,channel_id=$2 where id=$3',[pa,ca,run]);}});

it('actual collector wrapper denies revoked jobs and preserves creator for a lawful requesting collaborator',async()=>{const source=await readFile(new URL('../../worker.mjs',import.meta.url),'utf8');const start=source.indexOf('async function collectCompetitor(comp,');const end=source.indexOf('async function collectCompetitorScoped',start);if(start<0||end<0)throw Error('collector wrapper not located');const admitted:Record<string,unknown>[]=[];const collect=new Function('pool','requireResearchWorkerScope','withChannelAiSpendScope','collectCompetitorScoped',source.slice(start,end)+';return collectCompetitor;')(pool,requireResearchWorkerScope,async(_pool:unknown,_user:number,_channel:number,task:()=>Promise<void>)=>task(),async(row:Record<string,unknown>)=>{admitted.push(row);});const row=(await pool.query('select * from competitors where id=$1',[comp])).rows[0];await expect(collect(row,{userId:actor,projectId:pa})).rejects.toMatchObject({message:'research_project_access_denied'});expect(admitted).toHaveLength(0);await collect(row,{userId:collaborator,projectId:pa});expect(admitted).toHaveLength(1);expect(admitted[0]).toMatchObject({user_id:String(actor),researchScope:{userId:collaborator,projectId:pa}});});
it('actual Telegram collector rejects returned provider data when authority is revoked during fetch',async()=>{const source=await readFile(process.env.N21_COLLECTOR_SOURCE||new URL('../../worker.mjs',import.meta.url),'utf8');const start=source.indexOf('async function collectTelegramCompetitor(comp) {');const end=source.indexOf('async function collectInstagramCompetitor',start);if(start<0||end<0)throw Error('Telegram collector not located');let fakeReads=0;const scope=await requireResearchWorkerScope(pool,collaborator,ca,pa);const page={ok:true,title:'fixture',subscribers:1,posts:[{msgId:71,text:'after-revoke-data',views:1,reactions:0,media:'text',photoUrl:null,postedAt:new Date().toISOString()}]};const collect=new Function('readOnlyWork','pool','requireResearchWorkerScope','withResearchWorkerWrite','tgRead','tgMemberCount','fetchCompetitorPage','mskToday','upsertRadarPublicCorpus','summarizeTelegramPostingActivity','detectHits','console',source.slice(start,end)+';return collectTelegramCompetitor;')(createReadOnlyLifecycle(),pool,requireResearchWorkerScope,withResearchWorkerWrite,async()=>{fakeReads++;return{ok:true,result:{type:'channel',title:'fixture'}};},async()=>{fakeReads++;return 1;},async()=>{fakeReads++;await pool.query("update project_members set status='revoked',revoked_at=now() where project_id=$1 and user_id=$2",[pa,collaborator]);return page;},()=>new Date().toISOString().slice(0,10),async()=>{},()=>({}),async()=>{},{log(){},error(){},warn(){}});const row=(await pool.query('select * from competitors where id=$1',[comp])).rows[0];let denied=false;try{await collect({...row,researchScope:scope});}catch(error){denied=(error as Error).message==='research_project_access_denied';}expect(fakeReads).toBe(3);expect((await pool.query('select id from competitor_posts where competitor_id=$1',[comp])).rowCount).toBe(0);expect(denied).toBe(true);});

it('concurrent research additions cannot bypass the cumulative competitor count limit',async()=>{let reads=0;let releaseBarrier:()=>void=()=>{};let timer:ReturnType<typeof setTimeout>|undefined;const barrier=new Promise<void>(resolve=>{releaseBarrier=resolve;});state.pool={query:pool.query.bind(pool),connect:async()=>{const client=await pool.connect();return{release:()=>client.release(),query:async(sql:string,values?:unknown[])=>{const result=await client.query(sql,values);if(sql.includes('select count(*)::int as n from competitors')){reads++;if(!timer)timer=setTimeout(releaseBarrier,150);if(reads===3)releaseBarrier();await barrier;}return result;}};}} as unknown as pg.Pool;const existing=Number((await pool.query('select count(*) from competitors where channel_id=$1',[cb])).rows[0].count);const fixtureIds:number[]=[];for(let n=existing;n<19;n++)fixtureIds.push(Number((await pool.query("insert into competitors(user_id,channel_id,network,handle,status)values($1,$2,'tg',$3,'ready')returning id",[actor,cb,'quota-fill-'+n])).rows[0].id));try{const responses=await Promise.all(Array.from({length:6},(_,index)=>addCompetitor.POST(req('/api/competitors/add','POST',{channelId:cb,handle:'quota_race_'+index}))));expect(responses.filter(response=>response.status===200)).toHaveLength(1);expect(Number((await pool.query('select count(*) from competitors where channel_id=$1',[cb])).rows[0].count)).toBe(20);}finally{releaseBarrier();if(timer)clearTimeout(timer);state.pool=pool;await pool.query("delete from competitors where channel_id=$1 and handle like 'quota%'",[cb]);}});

it('explicit collaborator resume survives a later periodic collection without transferring creator identity',async()=>{state.actor=collaborator;state.project=pa;const response=await competitor.PATCH(req(`/api/competitors/${comp}`,'PATCH',{action:'resume'}),ctx());expect(response.status).toBe(200);const row=(await selectDueCompetitorSources(pool)).find((candidate:{id:number|string})=>Number(candidate.id)===comp);expect(row).toBeTruthy();const source=await readFile(new URL('../../worker.mjs',import.meta.url),'utf8');const start=source.indexOf('async function collectCompetitor(comp,');const end=source.indexOf('async function collectCompetitorScoped',start);let calls=0;const collect=new Function('pool','requireResearchWorkerScope','withChannelAiSpendScope','collectCompetitorScoped',source.slice(start,end)+';return collectCompetitor;')(pool,requireResearchWorkerScope,async(_pool:unknown,_user:number,_channel:number,task:()=>Promise<void>)=>task(),async(candidate:{researchScope:{userId:number}})=>{expect(candidate.researchScope.userId).toBe(collaborator);calls++;});try{await collect(row);}catch(error){if((error as Error).message!=='research_project_access_denied')throw error;}expect(calls).toBe(1);const stored=(await pool.query("select user_id,to_jsonb(competitors)->>'collection_requested_by_user_id' as collector from competitors where id=$1",[comp])).rows[0];expect(Number(stored.user_id)).toBe(actor);expect(Number(stored.collector)).toBe(collaborator);});

it('migration21 expands a legacy source schema without inventing a collection actor',async()=>{const before=Number((await pool.query('select count(*) from competitors')).rows[0].count);await pool.query('alter table competitors drop column collection_requested_by_user_id');await pool.query("delete from schema_migrations where name='20261021_competitor_collection_authority.sql'");await migrate({env:{DATABASE_URL:target.href},logger:{log(){}}});expect(Number((await pool.query('select count(*) from competitors')).rows[0].count)).toBe(before);expect((await pool.query('select collection_requested_by_user_id from competitors where id=$1',[comp])).rows[0].collection_requested_by_user_id).toBeNull();expect(Number((await pool.query('select user_id from competitors where id=$1',[comp])).rows[0].user_id)).toBe(actor);});

it.each(['bot-read', 'public-page'] as const)('N39: shutdown during %s preserves durable pending collection and a fresh worker resumes it', async (phase) => {
  const source = await readFile(new URL('../../worker.mjs', import.meta.url), 'utf8');
  const start = source.indexOf('async function collectTelegramCompetitor(comp) {');
  const end = source.indexOf('async function collectInstagramCompetitor', start);
  if (start < 0 || end < 0) throw Error('Telegram collector not located');
  const requestedAt = new Date('2026-09-05T00:00:00.000Z');
  await pool.query("update competitors set status='ready', title='retained-before-shutdown', collected_at=now(), sync_requested_at=$2, sync_started_at=null where id=$1", [comp, requestedAt]);
  const before = (await pool.query('select * from competitors where id=$1', [comp])).rows[0];
  const scope = await requireResearchWorkerScope(pool, collaborator, ca, pa);
  const page = { ok: true, title: 'verified-after-restart', subscribers: 1, posts: [{ msgId: 91, text: 'synthetic resumed collection', views: 1, reactions: 0, media: 'text', photoUrl: null, postedAt: new Date().toISOString() }] };
  function collector(lifecycle: ReturnType<typeof createReadOnlyLifecycle>, interrupt: boolean) {
    return new Function('readOnlyWork', 'pool', 'requireResearchWorkerScope', 'withResearchWorkerWrite', 'tgRead', 'tgMemberCount', 'fetchCompetitorPage', 'mskToday', 'upsertRadarPublicCorpus', 'summarizeTelegramPostingActivity', 'detectHits', 'console', source.slice(start, end) + ';return collectTelegramCompetitor;')(
      lifecycle, pool, requireResearchWorkerScope, withResearchWorkerWrite,
      async () => { if (interrupt && phase === 'bot-read') { lifecycle.stop(); lifecycle.throwIfStopped(); } return { ok: true, result: { type: 'channel', title: page.title } }; },
      async () => 1,
      async () => { if (interrupt && phase === 'public-page') { lifecycle.stop(); lifecycle.throwIfStopped(); } return page; },
      () => new Date().toISOString().slice(0, 10), async () => {}, () => ({}), async () => {}, { log() {}, error() {}, warn() {} },
    );
  }
  const cancelled = createReadOnlyLifecycle();
  const error = await collector(cancelled, true)({ ...before, researchScope: scope }).catch((failure: unknown) => failure);
  expect(cancelled.isCancellation(error)).toBe(true);
  const pending = (await pool.query('select * from competitors where id=$1', [comp])).rows[0];
  expect(pending.status).toBe('refreshing');
  expect(pending.title).toBe(before.title);
  expect(pending.collected_at).toEqual(before.collected_at);
  expect(pending.sync_requested_at).toEqual(requestedAt);
  expect(pending.sync_started_at).not.toBeNull();
  expect((await pool.query('select id from competitor_posts where competitor_id=$1', [comp])).rowCount).toBe(0);
  expect((await selectDueCompetitorSources(pool)).some((row: { id: string | number }) => Number(row.id) === comp)).toBe(true);
  const restarted = createReadOnlyLifecycle();
  await collector(restarted, false)({ ...pending, researchScope: scope });
  const completed = (await pool.query('select * from competitors where id=$1', [comp])).rows[0];
  expect(completed.status).toBe('ready');
  expect(completed.title).toBe(page.title);
  expect(completed.sync_requested_at).toBeNull();
  expect(completed.sync_started_at).toBeNull();
  expect(Number(completed.user_id)).toBe(actor);
  expect((await pool.query('select id from competitor_posts where competitor_id=$1', [comp])).rowCount).toBe(1);
});
